# docker-compose.yml (REEMPLAZAR COMPLETO)
services:
  db:
    image: postgres:15
    container_name: shift-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shift_aplication
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10
      start_period: 5s

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: shift-back
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./back/.env.docker
    ports:
      - "3001:3000"
    # IMPORTANT: NO host bind-mount of ./back here. Usamos la imagen construida.
    # volumes: removed for production image to avoid hiding /app contents

volumes:
  db_data:
