version: "3.8"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: shift_user
      POSTGRES_PASSWORD: shift_pass
      POSTGRES_DB: shift_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://shift_user:shift_pass@db:5432/shift_db
      NODE_ENV: development
      PORT: 3000
    restart: unless-stopped

volumes:
  db-data:
