version: "3.8"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: shift_user
      POSTGRES_PASSWORD: shift_pass
      POSTGRES_DB: shift_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      # aquí se leen las variables del contenedor
      DATABASE_URL: postgres://shift_user:shift_pass@db:5432/shift_db
      NODE_ENV: development
      PORT: 3000
      # Si seguís usando Supabase podés poner las variables; si no, borralas.
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
    # para desarrollo podés montar código (opcional)
    volumes:
      - ./:/app
volumes:
  db-data:
